target-version = "py312"
line-length = 89

[lint]
select = ["ALL"]
ignore = [
    "ANN401",
    "ARG002",
    "ASYNC230",
    "ASYNC240",
    "B904",
    "BLE001",
    "C901",
    "COM812",
    "CPY001",
    "D100",
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    "D203",
    "D205",
    "D212",
    "D214",
    "D215",
    "D301",
    "D401",
    "D404",
    "D416",
    "D417",
    "DOC501",
    "DOC502",
    "E501",
    "E731",
    "FBT001",
    "FBT002",
    "FBT003",
    "G004",
    "PLR",
    "RET503",
    "RET504",
    "S311",
    "S404",
    "SIM102",
    "SIM105",
    "SIM108",
    "T201",
    "TRY003",
    "D101",
]
fixable = [
    "C401",
    "D200", "D202", "D213", "D411", "D413",
    "F401", "F541", "F632",
    "I",
    "RUF022",
    "TRY201",
    "UP037",
]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 72